### ISSUE TITLE
Getting Token Error

### ISSUE THREAD

**Issue by joegaudet** [john-d-pelingo/jira-link-issue-action#283]
Hey Have the following setup, and am getting errors.

```yaml

  jira-link:
    name: 'Add Jira Link'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Link Jira Issue
        uses: sbimochan/jira-link-commenter@v2.5
        with:
          jira-project-url: https://foodee.atlassian.net/browse
          ticket-regex-title: /^[A-Z,a-z]{2,}-\d{1,}/g

```

```Error: Parameter token or opts.auth is required```

Any guidance?
